[package]
name = "auth_api_axum"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tower-cookies = "0.11"
tower-http = { version = "0.6.8", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

# Database
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono", "migrate"] }
uuid = { version = "1.21", features = ["v4", "serde"] }
chrono = { version = "0.4.44", features = ["serde"] }

# Hashing
argon2 = "0.5.3"
sha2 = "0.10.9"

rand = "0.10"


# JWT
rustls = "0.23.37"
jsonwebtoken = {version = "10.3" , default-features = false, features = ["rust_crypto"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

# Environment
dotenv = "0.15"
anyhow = "1.0.102"