[package]
name = "rust_todo_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5"
actix-identity = "0.7"
actix-session = { version = "0.9", features = ["cookie-session"] }
argon2 = "0.5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.6", features = ["v4", "serde"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono", "migrate"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15"
anyhow = "1.0"                 # For easier error handling
thiserror = "1.0"              # Optional, for custom errors